---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# addNarrData

<!-- badges: start -->
<!-- badges: end -->

The goal of addNarrData is to add average NARR weather varaibles to your data based on `narr_cell` (an identifier for a 12 x 12 km NARR grid cell) and `start_date` and `end_date`. 

## Installation

Install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("geomarker-io/addNarrData")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example, eval = F}
library(addNarrData)
library(magrittr)

d <- tibble::tribble(
  ~id, ~VisitDate, ~narr_cell,
  51981, "3/8/17", 56772,
  77553, "2/6/12", 56772,
  52284, "6/18/13", 57121,
  96308, "2/25/19", 57121,
  78054, "9/20/17", 56773
) %>%
  dplyr::mutate(
    VisitDate = as.Date(VisitDate, format = "%m/%d/%y"),
    start_date = VisitDate - lubridate::days(7),
    end_date = VisitDate
  )

get_narr_data(d, narr_variables = c('air.2m', 'rhum.2m'))
```
